In [6]:
import numpy as np

In [66]:
import numpy as np
def DPChange(M,c,d):
#
# Arguments
# ========
# M the amount of change to be made
# c and array containing the coin denominations (in no particular order)
# d the number of denominations (ie the number of elements of c)
#
# Local Variables
# ===========
#
    bestNumCoins = np.zeros(M+1) #array containing the optimal number of coins
    bestComb = np.zeros((M+1,d))
    bestNumCoins[0] = 0
    
    for m in range (1,M+1):
        bestNumCoins[m] = M+1 #lo fijo en un valor cielo
        for i in range(d):
            if m >= c[i]:
                if bestNumCoins[m-c[i]] + 1 < bestNumCoins[m]:
                    bestNumCoins[m] = bestNumCoins[m-c[i]]+ 1
                    bestComb[m] = bestComb[m-c[i]]
                    bestComb[m][i] = bestComb[m][i]+1
    return bestNumCoins[M].astype(int),bestComb[M].astype(int)

M = 6
c = [1,3,4]
d = len(c)

print(DPChange(M,c,d))

(2, array([0, 2, 0]))


In [67]:
M = 6
c = [1,3,4]
d = len(c)

In [64]:
print(DPChange(M,c,d))

[[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 1.]
 [0. 2. 0.]]
(2, array([0, 2, 0]))


In [59]:
print(bestComb)

NameError: name 'bestComb' is not defined

In [55]:
a = np.zeros((10,5))

In [38]:
a[1][:] = 5

In [39]:
print(a)

[[0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [42]:
print(a[1])

[5. 5. 5. 5. 5.]


In [43]:
a[2] = a[1]

In [44]:
print(a)

[[0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
